#-------------------------------------------------------------------------------
# Makefile for Athena operating system.
#  Unified loading method.

.PHONY: build clean all re-make


build:
	echo "\e[1;33mNothing to build \e[0m"

clean:
	echo "\e[1;33mNothing to clean \e[0m"

all: build

re-make: clean build
